paths:
  /api/products:
    get:
      summary: Returns all registered products.
      tags:
        - Products
      responses:
        '200':
          description: Products successfully retrieved.
          content:
            aplication/json:
              schema:
                type: array
                items:                  
                  $ref: '#components/schemas/products'
        '500':
          description: Internal error, please check DB connection.
    post:
      summary: Create a new product.
      tags:
        - Products

  /api/products/{id}:
    get:
      summary: Retrieve the product with the selected ID.
      tags:
        - Products
      parameters:
      - name: id
        in: path
        required: true
        description: Id to get the product
        schema:
          type: string
      responses:
        '200':
          description: Product successfully retrieved.
        '404':
          description: Not Found, please check input values.
        '500':
          description: Internal error, please check DB connection.

    put:
      summary: Update a specific product.
      tags:
        - Products
      parameters:
      - name: id
        in: path
        required: true
        description: Id to Update the product
        schema:
          type: string
      requestBody:
        required: true
        content:
          aplication/json:
            schema:
              $ref: '#components/requestBodies/UpdateUser'
      responses:
        '200':
          description: Product successfully updated  
        '404':
          description: Not Found. Please check input values.
        '500':
          description: Internal error, please check DB connection.

    delete:
      summary: Delete a specific product.
      tags:
        - Products

components:
  schemas:
    products:
      type: object
      properties:
        _id:
          type: string
          description: Id generated by MongoDB.
          required: true
          unique: true
        title:
          type: string
          description: Product name.
          required: true
        description:
          type: string
          description: Product details.
          required: true
        category:
          type: string
          description: Product category.
          required: true
        thumbnail:
          type: array
          description: Product URL pictures.
          required: true
          default: ../public/img/notFound/image-not-found-scaled-640.png
        code:
          type: string
          description: Alphanumeric product code.
          required: true
          unique: true
          indexed: true
        price:
          type: number
          description: Current product price.
          required: true
        stock:
          type: number
          description: Current product quantity.
          required: true
        status:
          type: boolean
          description: Refers to product availability.
          required: true
          default: true
        owner:
          typer: string
          description: Email of the user who created the product.
          required: true
          default: admin
      example:
        _id: 64be6a98319f417bda5b9bb4
        title: Refined Concrete Bacon
        description: The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients
        category: Towels
        thumbnail: ../public/img/notFound/image-not-found-scaled-640.png
        code: JHG53D
        price: 123
        stock: 12
        status: true
        owner: admin
  requestBodies:
    UpdateUser:
      type: object
      properties:
        title:
          type: string
          description: New title of the product
        description:
          type: string
          description: New description of the product
        category:
          type: string
          description: New category of the product
        price:
          type: number
          description: New price of the product
        stock:
          type: number
          description: New stock of the product

        
        


