apiVersion: apps/v1
kind: Deployment
metadata:
  name: newdeploy
spec:
  selector:
  template:
    metadata:
      labels:
        app: kubeoperations
      spec: 
        containers:
          - name: kubecontainer
            image: etcsa044/pruebakuber:1
            ports: 
              - containerPort: 8080
            imagePullPolicy: 
            

